"""SRD 20.4 catalogue. Mutable copies are edited through Management APIs."""
CATALOG = {
    "STAFF_LOGIN": ("Your staff account is ready. Set your first password securely", "Akaunti yako ya kazi iko tayari. Weka nenosiri lako la kwanza kwa usalama"),
    "PHONE": ("Confirm your phone number", "Thibitisha namba yako ya simu"),
    "PASSWORD_RESET": ("Reset your Oweru Marketplace password", "Weka upya nenosiri lako la Oweru Marketplace"),
    "EMAIL_VERIFICATION": ("Verify your Oweru Marketplace email", "Thibitisha barua pepe yako ya Oweru Marketplace"),
    "IDENTITY_DECISION": ("Your identity review decision is ready", "Uamuzi wa ukaguzi wa utambulisho wako uko tayari"),
    "OWNER_PRICE": ("Confirm your price and bank account", "Thibitisha bei na akaunti yako ya benki"),
    "LEAD_CREATED": ("A new Marketplace enquiry is available", "Ombi jipya la Marketplace limepatikana"),
    "CONTACT_LISTER": ("I am interested in this property", "Ninapenda mali hii"),
    "PAYMENT_INSTRUCTIONS": ("Your bank-transfer payment instructions are available", "Maelekezo yako ya malipo ya benki yanapatikana"),
    "OWNER_RECEIPT": ("Confirm you received payment", "Thibitisha umepokea malipo"),
    "PAYOUT_PAID": ("Your agent payout has been recorded as paid", "Malipo yako ya udalali yamerekodiwa kuwa yamelipwa"),
    "FULL_CHECK_CONSENT": ("Consent to a Full Check", "Kubali ukaguzi kamili"),
    "FULL_CHECK_REPORT_READY": ("Your Full Check report is ready. Sign in to download", "Ripoti yako ya ukaguzi kamili iko tayari. Ingia ili kupakua"),
    "OFFICIAL_REGISTRATION": ("Register as a local official", "Jisajili kama afisa wa serikali ya mtaa"),
    "TASK_ASSIGNED": ("A new verification task is assigned to you", "Umepewa kazi mpya ya ukaguzi"),
    "PROFESSIONAL_LOGIN": ("Your professional account is ready. Set your password securely", "Akaunti yako ya kitaalamu iko tayari. Weka nenosiri lako kwa usalama"),
    "FREE_CHECK_REPORT": ("Your Free Check report is ready. This is not ownership verification", "Ripoti yako ya ukaguzi wa bure iko tayari. Huu si uthibitisho wa umiliki"),
    "COMPLAINT_NUMBER": ("Your complaint has been received", "Malalamiko yako yamepokelewa"),
    "COMPLAINT_UPDATE": ("Your complaint status or outcome has been updated", "Hali au matokeo ya malalamiko yako yamesasishwa"),
    "VERIFICATION_EXPIRING": ("Your verification expires within 30 days", "Uthibitisho wako unaisha ndani ya siku 30"),
    "FULL_CHECK_ORDERED": ("Your Full Check order has been received", "Ombi lako la ukaguzi kamili limepokelewa"),
    "FULL_CHECK_NOT_COMPLETED": ("Your Full Check could not be completed", "Ukaguzi wako kamili haukuweza kukamilika"),
    "PROFESSIONAL_DECLINED": ("A professional declined their assigned task", "Mtaalamu amekataa kazi aliyopewa"),
    "OWNER_CONTACT_REQUIRED": ("Provide the owner contact for your Full Check", "Toa mawasiliano ya mmiliki kwa ukaguzi kamili"),
    "FULL_CHECK_OFFER": ("You may order a Full Check before buying", "Unaweza kuagiza ukaguzi kamili kabla ya kununua"),
    "NON_TAX_ACKNOWLEDGEMENT": ("Receipt recorded. This is not a tax receipt", "Malipo yamerekodiwa. Hii si risiti ya kodi"),
    "NEEDS_OFFICIAL": ("A verification task needs an official", "Kazi ya ukaguzi inahitaji afisa"),
}
DEFAULTS = {key: {lang: f"Oweru Marketplace: {title}. {{reference}} {{details}} {{link}}" for lang, title in zip(["en", "sw"], titles)} for key, titles in CATALOG.items()}
