# Generated by Django 5.2.17 on 2026-10-04 07:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing_id', models.CharField(max_length=50, unique=True)),
                ('lister_kind', models.CharField(choices=[('OWNER', 'Owner'), ('AGENT', 'Agent')], max_length=16)),
                ('selling_price', models.DecimalField(decimal_places=0, max_digits=18)),
                ('owner_price', models.DecimalField(decimal_places=0, max_digits=18)),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian shilling')], default='TZS', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('UNDER_OFFER', 'Under offer'), ('SOLD', 'Sold'), ('WITHDRAWN', 'Withdrawn'), ('SUSPENDED', 'Suspended')], db_index=True, default='DRAFT', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('lister', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='properties.propertyrecord')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('selling_price__gt', 0)), name='listing_selling_price_positive'), models.CheckConstraint(condition=models.Q(('owner_price__gt', 0)), name='listing_owner_price_positive'), models.CheckConstraint(condition=models.Q(('lister_kind__in', ['OWNER', 'AGENT'])), name='listing_lister_kind_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'ACTIVE', 'UNDER_OFFER', 'SOLD', 'WITHDRAWN', 'SUSPENDED'])), name='listing_status_valid'), models.CheckConstraint(condition=models.Q(('currency__in', ['TZS'])), name='listing_currency_valid'), models.CheckConstraint(condition=models.Q(models.Q(('lister_kind', 'OWNER'), ('owner_price', models.F('selling_price'))), models.Q(('lister_kind', 'AGENT'), ('selling_price__gte', models.F('owner_price'))), _connector='OR'), name='listing_price_matches_lister_kind')],
            },
        ),
    ]
