# Generated by Django 5.2.17 on 2026-10-04 20:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        ('media', '0002_mediavariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='listings.listing')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing_photos', to='media.media')),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('listing', 'media'), name='listing_photo_unique_media'), models.UniqueConstraint(fields=('listing', 'position'), name='listing_photo_unique_position'), models.CheckConstraint(condition=models.Q(('position__gte', 0)), name='listing_photo_position_non_negative')],
            },
        ),
    ]
