# Generated by Django 5.2.17 on 2026-10-06 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
        ('listings', '0002_listingphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='rate_table',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='commissions.ratetable'),
        ),
    ]
