# Generated by Django 5.2.17 on 2026-10-06 05:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(unique=True)),
                ('total_rate', models.DecimalField(decimal_places=6, default='0.10', max_digits=7)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RateBand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lower', models.DecimalField(decimal_places=0, max_digits=18)),
                ('upper', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('oweru_rate', models.DecimalField(decimal_places=6, max_digits=7)),
                ('agent_rate', models.DecimalField(decimal_places=6, max_digits=7)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bands', to='commissions.ratetable')),
            ],
            options={
                'ordering': ['lower'],
            },
        ),
        migrations.AddConstraint(
            model_name='ratetable',
            constraint=models.CheckConstraint(condition=models.Q(('total_rate__gt', 0), ('total_rate__lt', 1)), name='rate_total_valid'),
        ),
        migrations.AddConstraint(
            model_name='rateband',
            constraint=models.UniqueConstraint(fields=('table', 'lower'), name='band_unique_lower'),
        ),
        migrations.AddConstraint(
            model_name='rateband',
            constraint=models.CheckConstraint(condition=models.Q(('lower__gte', 0), models.Q(('upper__isnull', True), ('upper__gte', models.F('lower')), _connector='OR')), name='band_bounds_valid'),
        ),
        migrations.AddConstraint(
            model_name='rateband',
            constraint=models.CheckConstraint(condition=models.Q(('agent_rate__gte', 0), ('agent_rate__lt', 1), ('oweru_rate__gte', 0), ('oweru_rate__lt', 1)), name='band_rates_valid'),
        ),
    ]
