# Generated by Django 5.2.18 on 2026-10-09 11:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.UUIDField()),
                ('reason', models.CharField(max_length=1000)),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administration_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
