# Generated by Django 5.2.17 on 2026-10-06 08:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_possibleduplicate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('DOCUMENT', 'Document'), ('FIELD', 'Field')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], db_index=True, default='PENDING', max_length=16)),
                ('submitted_at', models.DateTimeField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('subject_snapshot', models.JSONField(blank=True, default=dict)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='properties.propertyrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_verifications_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_verifications_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyVerificationEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_type', models.CharField(choices=[('TITLE_DOCUMENT', 'Title document'), ('FIELD_REPORT', 'Field report'), ('OFFICIAL_ATTESTATION', 'Official attestation')], max_length=32)),
                ('evidence_ref', models.CharField(max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_verification_evidence_created', to=settings.AUTH_USER_MODEL)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='verification.propertyverification')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='propertyverification',
            index=models.Index(fields=['property', 'kind', 'status', 'expires_at'], name='verification_effective_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyverification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reviewed_at__isnull', True), ('reviewed_by__isnull', True)), models.Q(('reviewed_at__isnull', False), ('reviewed_by__isnull', False)), _connector='OR'), name='verification_reviewer_pair'),
        ),
        migrations.AddConstraint(
            model_name='propertyverification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'APPROVED'), _negated=True), models.Q(('expires_at__isnull', False), ('reviewed_at__isnull', False), ('reviewed_by__isnull', False)), _connector='OR'), name='verification_approved_reviewed'),
        ),
        migrations.AddConstraint(
            model_name='propertyverification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REJECTED'), _negated=True), models.Q(('reviewed_at__isnull', False), ('reviewed_by__isnull', False), ('rejection_reason__isnull', False), models.Q(('rejection_reason', ''), _negated=True)), _connector='OR'), name='verification_rejected_reason'),
        ),
        migrations.AddConstraint(
            model_name='propertyverification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', False), ('status', 'REVOKED')), models.Q(('status', 'REVOKED'), _negated=True), _connector='OR'), name='verification_revoked_timestamp'),
        ),
    ]
