# Generated by Django 5.2.17 on 2026-10-06 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_possibleduplicate'),
        ('verification', '0002_propertyverification_verification_document_single_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='propertyverification',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'FIELD'), ('status__in', ['PENDING', 'APPROVED'])), fields=('property', 'kind'), name='verification_field_single_active'),
        ),
    ]
