# Generated by Django 5.2.17 on 2026-10-07 18:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_rate_table'),
        ('media', '0002_mediavariant'),
        ('payments', '0003_financial_notice'),
        ('properties', '0002_possibleduplicate'),
        ('site_capture', '0002_sitecapture_area_difference_percent_and_more'),
        ('verification', '0003_propertyverification_verification_field_single_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyverificationevidence',
            name='author_role',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='propertyverificationevidence',
            name='device',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='propertyverificationevidence',
            name='supersedes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction', to='verification.propertyverificationevidence'),
        ),
        migrations.CreateModel(
            name='VerificationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('FULL', 'Full check'), ('OUTSIDE_FULL', 'Outside full check')], max_length=16)),
                ('status', models.CharField(choices=[('AWAITING_PAYMENT', 'Awaiting payment'), ('AWAITING_CONSENT', 'Awaiting consent'), ('IN_PROGRESS', 'In progress'), ('UNDER_REVIEW', 'Under review'), ('PASSED', 'Passed'), ('PROBLEM_FOUND', 'Problem found'), ('NOT_COMPLETED', 'Not completed')], db_index=True, default='AWAITING_PAYMENT', max_length=24)),
                ('fee', models.DecimalField(decimal_places=0, max_digits=18)),
                ('scope_snapshot', models.JSONField()),
                ('subject_snapshot', models.JSONField()),
                ('payment_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('consent_due_at', models.DateTimeField(blank=True, null=True)),
                ('contact_due_at', models.DateTimeField(blank=True, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('owner_phone', models.CharField(blank=True, max_length=30)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('refresh_limit_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('invalidation_reason', models.CharField(blank=True, max_length=1000)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='full_checks', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='listings.listing')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consent_full_checks', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_jobs', to='properties.propertyrecord')),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_full_checks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('CONFIRM', 'Confirm'), ('DECLINE', 'Decline')], max_length=8)),
                ('recipient_phone', models.CharField(max_length=30)),
                ('context', models.JSONField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device', models.CharField(blank=True, max_length=2000)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('delivery', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.confirmationdelivery')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consent', to='verification.verificationjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=24)),
                ('reason', models.CharField(blank=True, max_length=1000)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='verification.verificationjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FullCheckReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('bank_reference', models.CharField(max_length=255)),
                ('tax_receipt_number', models.CharField(max_length=255, unique=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tax_receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.media')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipt', to='verification.verificationjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FullCheckProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('digest', models.CharField(max_length=64)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.media')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_proofs', to='verification.verificationjob')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(choices=[('PASSED', 'Passed'), ('PROBLEM_FOUND', 'Problem found'), ('NOT_COMPLETED', 'Not completed')], max_length=20)),
                ('risk_assessment', models.TextField()),
                ('not_checked', models.JSONField(default=list)),
                ('evidence_basis', models.JSONField()),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='verification.verificationjob')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(max_length=2)),
                ('version', models.PositiveIntegerField(default=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='verification.verificationjob')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.media')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='verification.verificationresult')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.JSONField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('SITE_CAPTURE', 'Site capture'), ('LOCAL_OFFICE', 'Local office'), ('PROFESSIONAL', 'Professional'), ('REGISTRY', 'Land Registry')], max_length=20)),
                ('status', models.CharField(choices=[('UNASSIGNED', 'UNASSIGNED'), ('NEEDS_OFFICIAL', 'NEEDS_OFFICIAL'), ('ASSIGNED', 'ASSIGNED'), ('ACCEPTED', 'ACCEPTED'), ('SUBMITTED', 'SUBMITTED'), ('TIMED_OUT', 'TIMED_OUT')], db_index=True, default='UNASSIGNED', max_length=20)),
                ('professional_type', models.CharField(blank=True, max_length=24)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('required', models.BooleanField(default=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verification_tasks', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='verification.verificationjob')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('purpose', models.CharField(max_length=40)),
                ('channels', models.JSONField(default=list)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='verification.verificationjob')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='verification.verificationtask')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_role', models.CharField(max_length=32)),
                ('author_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('device', models.CharField(max_length=255)),
                ('findings', models.JSONField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('capture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='site_capture.sitecapture')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='media.media')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction', to='verification.tasksubmission')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='verification.verificationtask')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=16)),
                ('reason', models.CharField(blank=True, max_length=1000)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_history', to='verification.verificationtask')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=1000)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.propertyrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('property', 'user'), name='verification_relationship_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='verificationjob',
            index=models.Index(fields=['property', 'status', 'expires_at'], name='full_check_effective_idx'),
        ),
        migrations.AddConstraint(
            model_name='verificationjob',
            constraint=models.CheckConstraint(condition=models.Q(('fee__gt', 0)), name='full_check_fee_positive'),
        ),
        migrations.AddConstraint(
            model_name='verificationjob',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['AWAITING_PAYMENT', 'AWAITING_CONSENT', 'IN_PROGRESS', 'UNDER_REVIEW', 'PASSED', 'PROBLEM_FOUND', 'NOT_COMPLETED'])), name='full_check_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='verificationjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PASSED'), _negated=True), models.Q(('completed_at__isnull', False), ('expires_at__isnull', False), ('verifier__isnull', False)), _connector='OR'), name='full_check_passed_dates'),
        ),
        migrations.AddConstraint(
            model_name='verificationjob',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('expires_at__gt', models.F('completed_at')), _connector='OR'), name='full_check_valid_expiry'),
        ),
        migrations.AddConstraint(
            model_name='verificationjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['AWAITING_PAYMENT', 'AWAITING_CONSENT', 'IN_PROGRESS', 'UNDER_REVIEW'])), fields=('buyer', 'property'), name='one_open_buyer_property_check'),
        ),
        migrations.AddConstraint(
            model_name='fullcheckproof',
            constraint=models.UniqueConstraint(fields=('job', 'digest'), name='full_check_proof_content_unique'),
        ),
        migrations.AddConstraint(
            model_name='verificationreport',
            constraint=models.UniqueConstraint(fields=('job', 'version'), name='full_check_report_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='verificationtask',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'PROFESSIONAL'), _negated=True), fields=('job', 'kind'), name='one_core_task_per_job'),
        ),
        migrations.AddConstraint(
            model_name='verificationtask',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'PROFESSIONAL')), fields=('job', 'professional_type'), name='one_professional_type_per_job'),
        ),
        migrations.AddConstraint(
            model_name='verificationtask',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['UNASSIGNED', 'NEEDS_OFFICIAL', 'ASSIGNED', 'ACCEPTED', 'SUBMITTED', 'TIMED_OUT'])), name='verification_task_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='verificationtask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['ASSIGNED', 'ACCEPTED']), _negated=True), ('assignee__isnull', False), _connector='OR'), name='verification_task_assigned_user'),
        ),
        migrations.AddConstraint(
            model_name='verificationnotice',
            constraint=models.UniqueConstraint(fields=('job', 'task', 'recipient', 'phone', 'purpose'), name='verification_notice_unique', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='tasksubmission',
            constraint=models.UniqueConstraint(fields=('task', 'version'), name='task_submission_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='tasksubmission',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='task_submission_version_positive'),
        ),
    ]
