# Generated by Django 5.2.17 on 2026-10-07 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0005_submitted_evidence_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='signed_and_stamped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verificationnotice',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verification_notices_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificationreport',
            name='assessment_snapshot',
            field=models.TextField(blank=True),
        ),
    ]
