# Generated by Django 5.2.17 on 2026-10-07 20:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_rate_table'),
        ('verification', '0007_full_check_database_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationLevelSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('calculated_at', models.DateTimeField()),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='verification_snapshot', to='listings.listing')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('level__gte', 0), ('level__lte', 3)), name='stored_verification_level_valid')],
            },
        ),
    ]
