# Generated by Django 5.2.17 on 2026-10-07 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_rate_table'),
        ('media', '0002_mediavariant'),
        ('payments', '0003_financial_notice'),
        ('properties', '0002_possibleduplicate'),
        ('verification', '0008_verificationlevelsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fullcheckreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='full_check_receipt_positive'),
        ),
        migrations.AddConstraint(
            model_name='ownerconsent',
            constraint=models.CheckConstraint(condition=models.Q(('decision__in', ['CONFIRM', 'DECLINE'])), name='full_check_consent_decision_valid'),
        ),
        migrations.AddConstraint(
            model_name='ownerconsent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('delivery__isnull', True)), models.Q(('actor__isnull', True), ('delivery__isnull', False)), _connector='OR'), name='full_check_consent_authority'),
        ),
        migrations.AddConstraint(
            model_name='ownerconsent',
            constraint=models.CheckConstraint(condition=models.Q(('recipient_phone', ''), _negated=True), name='full_check_consent_phone_required'),
        ),
        migrations.AddConstraint(
            model_name='verificationjob',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['FULL', 'OUTSIDE_FULL'])), name='full_check_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='verificationreport',
            constraint=models.CheckConstraint(condition=models.Q(('language__in', ['sw', 'en']), ('version__gte', 1)), name='full_check_report_version_language'),
        ),
        migrations.AddConstraint(
            model_name='verificationresult',
            constraint=models.CheckConstraint(condition=models.Q(('result__in', ['PASSED', 'PROBLEM_FOUND', 'NOT_COMPLETED'])), name='full_check_result_valid'),
        ),
        migrations.AddConstraint(
            model_name='verificationtask',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['SITE_CAPTURE', 'LOCAL_OFFICE', 'PROFESSIONAL', 'REGISTRY'])), name='verification_task_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='verificationtask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'PROFESSIONAL'), ('professional_type__in', ['AFISA_MIPANGO_MIJI', 'PLANNER', 'SURVEYOR'])), models.Q(models.Q(('kind', 'PROFESSIONAL'), _negated=True), ('professional_type', '')), _connector='OR'), name='verification_task_prof_type_valid'),
        ),
    ]
