# Generated by Django 5.2.18 on 2026-10-09 11:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0009_fullcheckreceipt_full_check_receipt_positive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationsetting',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SettingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('value', models.JSONField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='verification.verificationsetting')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('setting', 'version'), name='setting_history_version_unique')],
            },
        ),
    ]
