from types import MappingProxyType


LISTER_IDENTITY_CREATED = "LISTER_IDENTITY_CREATED"
LISTER_IDENTITY_UPDATED = "LISTER_IDENTITY_UPDATED"
LISTER_IDENTITY_SUBMITTED = "LISTER_IDENTITY_SUBMITTED"
LISTER_IDENTITY_APPROVED = "LISTER_IDENTITY_APPROVED"
LISTER_IDENTITY_REJECTED = "LISTER_IDENTITY_REJECTED"
LISTER_IDENTITY_EXPIRED = "LISTER_IDENTITY_EXPIRED"

LISTER_IDENTITY_AUDIT_ACTIONS = MappingProxyType({
    LISTER_IDENTITY_CREATED: "Lister identity created",
    LISTER_IDENTITY_UPDATED: "Lister identity updated",
    LISTER_IDENTITY_SUBMITTED: "Lister identity submitted",
    LISTER_IDENTITY_APPROVED: "Lister identity approved",
    LISTER_IDENTITY_REJECTED: "Lister identity rejected",
    LISTER_IDENTITY_EXPIRED: "Lister identity expired",
})
