# Generated by Django 5.2.17 on 2026-10-06

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0002_possibleduplicate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteCapture",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("capture_id", models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ("captured_at", models.DateTimeField(editable=False)),
                ("observed_point", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("observed_boundary", django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("SUBMITTED", "Submitted")], db_index=True, default="DRAFT", max_length=16)),
                ("captured_by", models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name="site_captures", to=settings.AUTH_USER_MODEL)),
                ("property", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="site_captures", to="properties.propertyrecord")),
            ],
            options={
                "ordering": ["-captured_at", "-created_at"],
                "indexes": [models.Index(fields=["property", "status", "captured_at"], name="sitecap_prop_status_idx")],
            },
        ),
    ]
