# Generated by Django 5.2.17 on 2026-10-07 18:45

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_capture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecapture',
            name='area_difference_percent',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='sitecapture',
            name='measured_area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='sitecapture',
            name='review_flags',
            field=models.JSONField(default=list, editable=False),
        ),
        migrations.CreateModel(
            name='CaptureCorner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('accuracy_m', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observed_at', models.DateTimeField()),
                ('device', models.CharField(max_length=255)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corners', to='site_capture.sitecapture')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('capture', 'sequence'), name='capture_corner_sequence_unique'), models.CheckConstraint(condition=models.Q(('accuracy_m__gte', 0)), name='capture_corner_accuracy_nonnegative')],
            },
        ),
    ]
