# Generated by Django 5.2.17 on 2026-10-07 19:57

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_mediavariant'),
        ('site_capture', '0002_sitecapture_area_difference_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecapture',
            name='overlap_findings',
            field=models.JSONField(default=list, editable=False),
        ),
        migrations.CreateModel(
            name='CaptureAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('CAMERA', 'Camera'), ('UPLOAD', 'Gallery')], max_length=10)),
                ('flags', models.JSONField(default=list)),
                ('distance_m', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='site_capture.sitecapture')),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='media.media')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicMapLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('source_reference', models.CharField(max_length=1000)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('active', models.BooleanField(default=True)),
                ('loaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
