# Generated by Django 5.2.17 on 2026-10-07 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_capture', '0004_capture_media_guards'),
        ('verification', '0009_fullcheckreceipt_full_check_receipt_positive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecapture',
            name='verification_task',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_captures', to='verification.verificationtask'),
        ),
    ]
