# Generated by Django 5.2.17 on 2026-10-03 23:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_id', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('LAND', 'Land'), ('HOUSE', 'House'), ('COMMERCIAL', 'Commercial')], max_length=20)),
                ('pin', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('stated_size', models.DecimalField(decimal_places=2, max_digits=18)),
                ('size_unit', models.CharField(max_length=20)),
                ('title_type', models.CharField(choices=[('REGISTERED_TITLE', 'Registered title'), ('RESIDENTIAL_LICENCE', 'Residential licence'), ('SALE_AGREEMENT', 'Sale agreement'), ('CCRO', 'CCRO'), ('VILLAGE_RECORDS', 'Village records'), ('NONE', 'None'), ('UNKNOWN', 'Unknown')], max_length=32)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='property_records_created', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_records', to='localities.district')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_records', to='localities.locality')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_records', to='localities.region')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_records', to='localities.ward')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('stated_size__gt', 0)), name='property_stated_size_positive')],
            },
        ),
    ]
