# Generated by Django 5.2.17 on 2026-10-04 20:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PossibleDuplicate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED_DUPLICATE', 'Confirmed duplicate'), ('NOT_DUPLICATE', 'Not duplicate')], db_index=True, default='PENDING', max_length=32)),
                ('signals', models.JSONField(default=list)),
                ('distance_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('size_difference_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=1000)),
                ('property_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='possible_duplicates_as_a', to='properties.propertyrecord')),
                ('property_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='possible_duplicates_as_b', to='properties.propertyrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_possible_duplicates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('property_a', 'property_b'), name='possible_duplicate_unique_pair'), models.CheckConstraint(condition=models.Q(('property_a', models.F('property_b')), _negated=True), name='possible_duplicate_no_self_pair'), models.CheckConstraint(condition=models.Q(('distance_meters__isnull', True), ('distance_meters__gte', 0), _connector='OR'), name='possible_duplicate_distance_non_negative'), models.CheckConstraint(condition=models.Q(('size_difference_percent__isnull', True), ('size_difference_percent__gte', 0), _connector='OR'), name='possible_duplicate_size_diff_non_negative')],
            },
        ),
    ]
