# Generated by Django 5.2.18 on 2026-10-09 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localities', '0001_initial'),
        ('properties', '0002_possibleduplicate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrecord',
            name='is_outside_check',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_records_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_records', to='localities.district'),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_records', to='localities.locality'),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_records', to='localities.region'),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_records', to='localities.ward'),
        ),
        migrations.AddConstraint(
            model_name='propertyrecord',
            constraint=models.CheckConstraint(condition=models.Q(('is_outside_check', True), models.Q(('created_by__isnull', False), ('district__isnull', False), ('locality__isnull', False), ('region__isnull', False), ('ward__isnull', False)), _connector='OR'), name='property_normal_context_required'),
        ),
    ]
