# Generated by Django 5.2.18 on 2026-10-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_deletion_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='management_position',
            field=models.CharField(blank=True, choices=[('DIRECTOR', 'Director'), ('HEAD_OPERATIONS', 'Head of Operations')], editable=False, max_length=20),
        ),
    ]
