# Generated by Django 5.2.18 on 2026-10-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_management_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='administration_version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
