# Generated by Django 5.2.17 on 2026-10-06 05:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
        ('listings', '0002_listingphoto'),
        ('properties', '0002_possibleduplicate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_whatsapp', models.CharField(max_length=30)),
                ('source', models.CharField(choices=[('ENQUIRY', 'Enquiry'), ('WHATSAPP_CONTACT', 'Whatsapp Contact'), ('VIEWING_REQUEST', 'Viewing Request')], max_length=24)),
                ('stage', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('VIEWING', 'Viewing'), ('NEGOTIATION', 'Negotiation'), ('CLOSING', 'Closing'), ('WON', 'Won'), ('LOST', 'Lost')], default='NEW', max_length=16)),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('lost_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buyer_leads', to=settings.AUTH_USER_MODEL)),
                ('lister', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lister_leads', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='listings.listing')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='properties.propertyrecord')),
            ],
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='leads.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_stage', models.CharField(max_length=16)),
                ('to_stage', models.CharField(max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='leads.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LostLeadReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lost_lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_reviews', to='leads.lead')),
                ('sold_deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lost_lead_reviews', to='deals.deal')),
            ],
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lister', 'stage', 'follow_up_at'], name='lead_lister_pipeline_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['property', 'buyer', 'lost_at'], name='lead_lost_buyer_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('stage__in', ['NEW', 'CONTACTED', 'VIEWING', 'NEGOTIATION', 'CLOSING', 'WON', 'LOST'])), name='lead_stage_valid'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['ENQUIRY', 'WHATSAPP_CONTACT', 'VIEWING_REQUEST'])), name='lead_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('buyer_name', ''), _negated=True), models.Q(('buyer_whatsapp', ''), _negated=True)), name='lead_contact_required'),
        ),
        migrations.AddConstraint(
            model_name='lostleadreview',
            constraint=models.UniqueConstraint(fields=('lost_lead', 'sold_deal'), name='lost_sale_review_unique'),
        ),
    ]
