# Generated by Django 5.2.17 on 2026-10-04 15:31

import apps.media.models
import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_id', models.CharField(db_index=True, default=apps.media.models.generate_media_id, editable=False, max_length=20, unique=True)),
                ('object_id', models.UUIDField()),
                ('file_key', models.CharField(max_length=1024, validators=[apps.media.models.validate_file_key])),
                ('source', models.CharField(choices=[('UPLOAD', 'Upload'), ('CAMERA', 'Camera'), ('SITE_CAPTURE', 'Site capture')], default='UPLOAD', max_length=20)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('captured_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('device', models.CharField(blank=True, max_length=255)),
                ('file_hash', models.CharField(blank=True, max_length=128)),
                ('mime_type', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_items', to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='media_size_bytes_positive')],
            },
        ),
    ]
