# Generated by Django 5.2.17 on 2026-10-04 20:03

import apps.media.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('ORIGINAL', 'Original'), ('DISPLAY', 'Display')], max_length=20)),
                ('file_key', models.CharField(max_length=1024, validators=[apps.media.models.validate_file_key])),
                ('mime_type', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='media.media')),
            ],
            options={
                'ordering': ['kind'],
                'constraints': [models.UniqueConstraint(fields=('media', 'kind'), name='media_variant_unique_kind'), models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='media_variant_size_bytes_positive'), models.CheckConstraint(condition=models.Q(('width__gt', 0)), name='media_variant_width_positive'), models.CheckConstraint(condition=models.Q(('height__gt', 0)), name='media_variant_height_positive')],
            },
        ),
    ]
