# Generated by Django 5.2.17 on 2026-10-03 13:38

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_locality_region_name_ci')],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='localities.region')),
            ],
            options={
                'ordering': ['region__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='localities.district')),
            ],
            options={
                'ordering': ['district__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('street', 'Street'), ('village', 'Village')], max_length=16)),
                ('approved', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localities', to='localities.ward')),
            ],
            options={
                'ordering': ['ward__name', 'kind', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(models.F('region'), django.db.models.functions.text.Lower('name'), name='uniq_locality_district_region_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='ward',
            constraint=models.UniqueConstraint(models.F('district'), django.db.models.functions.text.Lower('name'), name='uniq_locality_ward_district_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='locality',
            constraint=models.UniqueConstraint(models.F('ward'), models.F('kind'), django.db.models.functions.text.Lower('name'), name='uniq_locality_ward_kind_name_ci'),
        ),
    ]
