# Generated by Django 5.2.17 on 2026-10-06 05:29

import apps.deals.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0002_mediavariant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_whatsapp', models.CharField(max_length=30)),
                ('lister_kind', models.CharField(max_length=16)),
                ('owner_price', models.DecimalField(decimal_places=0, max_digits=18)),
                ('final_selling_price', models.DecimalField(decimal_places=0, max_digits=18)),
                ('total_rate', models.DecimalField(decimal_places=6, max_digits=7)),
                ('oweru_rate', models.DecimalField(decimal_places=6, max_digits=7)),
                ('buyer_to_owner', models.DecimalField(decimal_places=0, max_digits=18)),
                ('buyer_to_oweru', models.DecimalField(decimal_places=0, max_digits=18)),
                ('oweru_keeps', models.DecimalField(decimal_places=0, max_digits=18)),
                ('agent_payout', models.DecimalField(decimal_places=0, max_digits=18)),
                ('payment_reference', models.CharField(default=apps.deals.models.payment_reference, editable=False, max_length=40, unique=True)),
                ('state', models.CharField(default='OPEN', max_length=16)),
                ('agreement_price_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('agreement_approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='media.media')),
                ('agreement_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_deal_agreements', to=settings.AUTH_USER_MODEL)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer_deals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
