# Generated by Django 5.2.17 on 2026-10-06 05:29

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commissions', '0001_initial'),
        ('deals', '0001_initial'),
        ('leads', '0001_initial'),
        ('listings', '0002_listingphoto'),
        ('properties', '0002_possibleduplicate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deal', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='deal',
            name='lister',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lister_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='deal',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.propertyrecord'),
        ),
        migrations.AddField(
            model_name='deal',
            name='rate_band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commissions.rateband'),
        ),
        migrations.AddField(
            model_name='deal',
            name='rate_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commissions.ratetable'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['buyer', 'state'], name='deal_buyer_state_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['lister', 'state'], name='deal_lister_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['OPEN', 'COMPLETE'])), name='deal_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'OPEN')), fields=('listing',), name='deal_one_open_listing'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('final_selling_price__gt', 0), ('owner_price__gt', 0)), name='deal_prices_positive'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('buyer_to_owner__gte', 0), ('buyer_to_oweru__gte', 0), ('oweru_keeps__gte', 0), ('agent_payout__gte', 0)), name='deal_money_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('final_selling_price', django.db.models.expressions.CombinedExpression(models.F('buyer_to_owner'), '+', models.F('buyer_to_oweru')))), name='deal_transfers_reconcile'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('buyer_to_oweru', django.db.models.expressions.CombinedExpression(models.F('oweru_keeps'), '+', models.F('agent_payout')))), name='deal_oweru_reconcile'),
        ),
    ]
