# Generated by Django 5.2.17 on 2026-10-06 05:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0002_initial'),
        ('listings', '0003_listing_rate_table'),
        ('media', '0002_mediavariant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(max_length=32)),
                ('recipient', models.CharField(max_length=30)),
                ('token_digest', models.CharField(max_length=64)),
                ('delivery_token', models.CharField(max_length=100)),
                ('context', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, max_length=16)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=2000)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='deals.deal')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='listings.listing')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_confirmations_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_scope', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=64)),
                ('resource', models.UUIDField()),
                ('key', models.CharField(max_length=128)),
                ('fingerprint', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('actor_scope', 'operation', 'resource', 'key'), name='financial_idempotency_scope')],
            },
        ),
        migrations.CreateModel(
            name='OfficialTaxReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=255, unique=True)),
                ('kind', models.CharField(choices=[('EFD', 'EFD'), ('VFD', 'VFD')], max_length=8)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tax_receipt', to='deals.deal')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.media')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OwnerContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('whatsapp', models.CharField(max_length=30)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_owner_price', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('decision', models.CharField(blank=True, max_length=16)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='owner_contact', to='listings.listing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=30)),
                ('confirmed_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_phone_confirmation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_oweru', models.BooleanField(default=False)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_account', to=settings.AUTH_USER_MODEL)),
                ('owner_contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_account', to='payments.ownercontact')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_oweru', False), ('owner_contact__isnull', True), ('user__isnull', False)), models.Q(('is_oweru', False), ('owner_contact__isnull', False), ('user__isnull', True)), models.Q(('is_oweru', True), ('owner_contact__isnull', True), ('user__isnull', True)), _connector='OR'), name='bank_holder_exclusive'), models.UniqueConstraint(condition=models.Q(('is_oweru', True)), fields=('is_oweru',), name='one_oweru_bank')],
            },
        ),
        migrations.CreateModel(
            name='PaymentConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer', models.CharField(max_length=16)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('bank_reference', models.CharField(max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_confirmations', to='deals.deal')),
                ('delivery', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.confirmationdelivery')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('deal', 'transfer'), name='confirmation_transfer_unique'), models.CheckConstraint(condition=models.Q(('amount__gte', 0), ('transfer__in', ['OWNER', 'OWERU'])), name='confirmation_context_valid')],
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer', models.CharField(choices=[('OWNER', 'Owner'), ('OWERU', 'Oweru')], max_length=16)),
                ('digest', models.CharField(max_length=64)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_proofs', to='deals.deal')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.media')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('deal', 'transfer', 'digest'), name='proof_content_unique'), models.CheckConstraint(condition=models.Q(('transfer__in', ['OWNER', 'OWERU'])), name='proof_transfer_valid')],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('status', models.CharField(default='PENDING', max_length=16)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('hold_reason', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('bank_reference', models.CharField(blank=True, max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_payouts', to=settings.AUTH_USER_MODEL)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout', to='deals.deal')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payouts', to=settings.AUTH_USER_MODEL)),
                ('proof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='media.media')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payout_amount_nonnegative'), models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'DUE', 'PAID', 'ON_HOLD'])), name='payout_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='PayoutBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_reference', models.CharField(max_length=255)),
                ('is_open', models.BooleanField(default=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_blocks', to='deals.deal')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('deal', 'external_reference'), name='complaint_block_unique')],
            },
        ),
    ]
