# Generated by Django 5.2.17 on 2026-10-07 00:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalOfficialProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('official_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('official_number', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='local_official_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['official_id'],
            },
        ),
        migrations.CreateModel(
            name='OfficialJurisdictionAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('scope_type', models.CharField(choices=[('REGION', 'Region'), ('DISTRICT', 'District'), ('WARD', 'Ward')], max_length=16)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], db_index=True, default='ACTIVE', max_length=16)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='official_jurisdictions_assigned', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='official_assignments', to='localities.district')),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jurisdiction_assignments', to='local_officials.localofficialprofile')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='official_assignments', to='localities.region')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='official_jurisdictions_revoked', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='official_assignments', to='localities.ward')),
            ],
            options={
                'ordering': ['-starts_at', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='localofficialprofile',
            constraint=models.CheckConstraint(condition=models.Q(('official_number', ''), _negated=True), name='local_official_number_not_blank'),
        ),
        migrations.AddIndex(
            model_name='officialjurisdictionassignment',
            index=models.Index(fields=['official', 'status', 'starts_at'], name='official_scope_effective_idx'),
        ),
        migrations.AddConstraint(
            model_name='officialjurisdictionassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('district__isnull', True), ('region__isnull', False), ('scope_type', 'REGION'), ('ward__isnull', True)), models.Q(('district__isnull', False), ('region__isnull', True), ('scope_type', 'DISTRICT'), ('ward__isnull', True)), models.Q(('district__isnull', True), ('region__isnull', True), ('scope_type', 'WARD'), ('ward__isnull', False)), _connector='OR'), name='official_scope_exact_area'),
        ),
        migrations.AddConstraint(
            model_name='officialjurisdictionassignment',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('expires_at__gt', models.F('starts_at')), _connector='OR'), name='official_scope_valid_period'),
        ),
        migrations.AddConstraint(
            model_name='officialjurisdictionassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_by__isnull', True), ('status', 'ACTIVE')), models.Q(('revoked_at__isnull', False), ('revoked_by__isnull', False), ('status', 'REVOKED')), _connector='OR'), name='official_scope_revocation_pair'),
        ),
        migrations.AddConstraint(
            model_name='officialjurisdictionassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'REGION'), ('status', 'ACTIVE')), fields=('official', 'region'), name='official_active_region_unique'),
        ),
        migrations.AddConstraint(
            model_name='officialjurisdictionassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'DISTRICT'), ('status', 'ACTIVE')), fields=('official', 'district'), name='official_active_district_unique'),
        ),
        migrations.AddConstraint(
            model_name='officialjurisdictionassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'WARD'), ('status', 'ACTIVE')), fields=('official', 'ward'), name='official_active_ward_unique'),
        ),
    ]
