# Generated by Django 5.2.17 on 2026-10-07 18:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_officials', '0001_initial'),
        ('localities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialLocalityCoverage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='official_coverage', to='localities.locality')),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locality_coverage', to='local_officials.localofficialprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['locality', 'revoked_at'], name='official_exact_locality_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('official', 'locality'), name='official_exact_locality_active'), models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('expires_at__gt', models.F('starts_at')), _connector='OR'), name='official_locality_valid_period')],
            },
        ),
    ]
