# Generated by Django 5.2.18 on 2026-10-09 11:28

import apps.complaints.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0004_deal_cancelled_state'),
        ('media', '0002_mediavariant'),
        ('properties', '0003_propertyrecord_is_outside_check_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=apps.complaints.models.number, max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('complainant_role', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('FAKE_LISTING', 'FAKE_LISTING'), ('WRONG_LISTING', 'WRONG_LISTING'), ('CONDUCT', 'CONDUCT'), ('PAYMENT', 'PAYMENT'), ('PAYOUT', 'PAYOUT'), ('PRIVACY', 'PRIVACY'), ('VERIFICATION', 'VERIFICATION'), ('OTHER', 'OTHER')], max_length=20)),
                ('source', models.CharField(choices=[('WEB', 'WEB'), ('WHATSAPP', 'WHATSAPP'), ('EMAIL', 'EMAIL')], max_length=10)),
                ('language', models.CharField(default='sw', max_length=2)),
                ('description', models.TextField()),
                ('route', models.CharField(max_length=20)),
                ('status', models.CharField(db_index=True, default='RECEIVED', max_length=24)),
                ('version', models.PositiveIntegerField(default=1)),
                ('outcome', models.TextField(blank=True)),
                ('reasons', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgement_due_at', models.DateTimeField()),
                ('resolution_due_at', models.DateTimeField(db_index=True)),
                ('final_review_requested_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='deals.deal')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handled_complaints', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='properties.propertyrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='complaints.complaint')),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='media.media')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComplaintHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=24)),
                ('reason', models.TextField()),
                ('version', models.PositiveIntegerField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='complaints.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(max_length=30)),
                ('version', models.PositiveIntegerField()),
                ('channels', models.JSONField()),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notices', to='complaints.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('from_complainant', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='complaints.complaint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['RECEIVED', 'IN_REVIEW', 'WAITING_INFORMATION', 'RESOLVED', 'UNDER_FINAL_REVIEW', 'CLOSED'])), name='complaint_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['FAKE_LISTING', 'WRONG_LISTING', 'CONDUCT', 'PAYMENT', 'PAYOUT', 'PRIVACY', 'VERIFICATION', 'OTHER'])), name='complaint_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='complainthistory',
            constraint=models.UniqueConstraint(fields=('complaint', 'version'), name='complaint_history_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='complaintnotice',
            constraint=models.UniqueConstraint(fields=('complaint', 'purpose', 'version'), name='complaint_notice_unique'),
        ),
    ]
