# Generated by Django 5.2.17 on 2026-10-07 19:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional_type', models.CharField(choices=[('AFISA_MIPANGO_MIJI', 'Afisa Mipango Miji'), ('PLANNER', 'Planner'), ('SURVEYOR', 'Surveyor')], max_length=24)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('national_id_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
                ('verified_at', models.DateTimeField()),
                ('districts', models.ManyToManyField(related_name='professional_profiles', to='localities.district')),
                ('regions', models.ManyToManyField(related_name='professional_profiles', to='localities.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professionals_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['professional_type', 'status'], name='professional_active_type_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('professional_type__in', ['AFISA_MIPANGO_MIJI', 'PLANNER', 'SURVEYOR'])), name='professional_type_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'INACTIVE'])), name='professional_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('registration_number', ''), _negated=True), models.Q(('national_id_number', ''), _negated=True)), name='professional_registration_required')],
            },
        ),
    ]
