# Generated by Django 5.2.18 on 2026-10-09 11:17

import apps.free_checks.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0002_mediavariant'),
        ('properties', '0002_possibleduplicate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=apps.free_checks.models.reference, max_length=30, unique=True)),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('language', models.CharField(default='sw', max_length=2)),
                ('description', models.CharField(max_length=4000)),
                ('external_url', models.URLField(blank=True, max_length=1000)),
                ('verdicts', models.JSONField()),
                ('expires_at', models.DateTimeField()),
                ('request_key', models.CharField(max_length=128)),
                ('input_digest', models.CharField(max_length=64)),
                ('token_digest', models.CharField(max_length=64)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='properties.propertyrecord')),
            ],
        ),
        migrations.CreateModel(
            name='FreeCheckLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('free_check', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prospect', to='free_checks.freecheck')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreeCheckPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('free_check', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='free_checks.freecheck')),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='media.media')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreeCheckReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('free_check', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='free_checks.freecheck')),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='media.media')),
            ],
        ),
        migrations.AddConstraint(
            model_name='freecheck',
            constraint=models.UniqueConstraint(fields=('phone', 'request_key'), name='free_check_request_unique'),
        ),
        migrations.AddConstraint(
            model_name='freecheck',
            constraint=models.CheckConstraint(condition=models.Q(('language__in', ['sw', 'en'])), name='free_check_language_valid'),
        ),
        migrations.AddConstraint(
            model_name='freecheckreport',
            constraint=models.UniqueConstraint(fields=('free_check', 'version'), name='free_report_version_unique'),
        ),
    ]
